### ISSUE TITLE
Goldsack Rotation

### ISSUE THREAD

**Issue by Babalela01** [Elzahn/IMY300#22]
Fix goldsack rotation, Or are ther egoing to be other loot models?

**Comment by Elzahn** [comment]
Dink Tania hanteer die, weet nie van ander models nie. So ver is die plan om die model self te draai

**Comment by TaniaRall** [comment]
Is die rotation nou reg? (as die subject ge-close is)

On Wed, Jul 29, 2015 at 7:42 PM, Elzahn <notifications@github.com> wrote:

> Closed #22 <https://github.com/Elzahn/IMY300/issues/22>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elzahn/IMY300/issues/22#event-368609182>.
>



-- 

*Tania Rall ...*

**Comment by Elzahn** [comment]
Jip sorry het vergeet on dit om die group te sit het uitgefigure hoe om dit te fix :)
