### ISSUE TITLE
Character is movable while loading

### ISSUE THREAD

**Issue by Elzahn** [Elzahn/IMY300#38]
Die character moenie kan loop terwyl die game load nie, maar ons kan nie die game pause nie

**Comment by TaniaRall** [comment]
kan mens nie wag vir die map om klaar te load en dan eers die character
load nie.. dan is dit ook nie nodig om die character hoog te load
voordietyd sodat die monsters dit nie kan attack nie...

On Sat, Aug 1, 2015 at 7:20 PM, Elzahn <notifications@github.com> wrote:

> Die character moenie kan loop terwyl die game load nie, maar ons kan nie
> die game pause nie
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Elzahn/IMY300/issues/38>.
>



-- 

*Tania Rall ...*

**Comment by Elzahn** [comment]
Geen idee of dit moontlik is nie ek dink nie eers hy load die character as jy die nuwe scene load nie since die character nooit gedestroy word nie hy bly net bestaan vanaf die eerste scene.
